FROM golang:1.12.0-alpine3.9 as build-env
RUN apk add --update --no-cache ca-certificates git
RUN mkdir /app
WORKDIR /app
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
RUN go build -o main .

FROM scratch
COPY --from=build-env /go/bin/app /go/bin/app
ENTRYPOINT ["/go/bin/app api"]